<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <PackageId>Security.Sanitization</PackageId>
    <Version>2.1.4</Version>
    <Authors>Curious Technical Team</Authors>
    <Company>Curious</Company>
    <Description>Middleware to sanitize HTTP headers and JSON request bodies</Description>
    <PackageTags>security;sanitizer;aspnetcore;xss</PackageTags>
    <RepositoryUrl>https://github.com/NtshetsoPele/XssPrevention-Api</RepositoryUrl>
    <PackageReleaseNotes>Header/body sanitization</PackageReleaseNotes>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" Version="9.0.886" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>